// <auto-generated />
namespace Hrm.Data.EF.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Test : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Test));
        
        string IMigrationMetadata.Id
        {
            get { return "201305021051145_Test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
